name: Build and Publish

on:
  release:
    types: [created]

env:
  NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
  PROJECT_NAME: DevStacks.WebApi.Core

jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: https://api.nuget.org/v3/index.json

      - name: Build .NET Library
        run: dotnet build $PROJECT_NAME

      - name: Create the package
        run: dotnet pack --configuration Release $PROJECT_NAME

      - name: Publish the package to NuGet
        run: dotnet nuget push $PROJECT_NAME/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
